"""added likes

Revision ID: 46183b3ba60f
Revises: ee1ce3adfd61
Create Date: 2023-12-06 00:30:28.132153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46183b3ba60f'
down_revision = 'ee1ce3adfd61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
