"""edited table names

Revision ID: c5dea1b61959
Revises: eb75a419ee39
Create Date: 2023-12-01 14:23:58.647676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5dea1b61959'
down_revision = 'eb75a419ee39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cheese', schema=None) as batch_op:
        batch_op.drop_index('ix_cheese_brand')
        batch_op.drop_index('ix_cheese_origin')
        batch_op.drop_column('origin')
        batch_op.drop_column('brand')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('cheese', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('origin', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_cheese_origin', ['origin'], unique=False)
        batch_op.create_index('ix_cheese_brand', ['brand'], unique=False)

    # ### end Alembic commands ###
